In [2]:
import pandas as pd
import numpy as np

In [5]:
s1 = pd.Series([i for i in range(1, 11)])
s1 = pd.Series([i for i in range(1, 11)], index=[i for i in range(1, 11)])
s1 = pd.Series((i for i in range(1, 11)), index=[i for i in range(1, 11)])
# s1

s2 = pd.Series({chr(i): i for i in range(97, 97 + 10)})
# s2 = pd.Series({chr(i): i for i in range(97, 97 + 10)}, index=['a', 'b'])
# s2 = pd.Series({chr(i): i for i in range(97, 97 + 10)}, index=['x', 'b'])
s2.loc['a']
# s2

97

In [14]:
s1 = pd.Series([i for i in range(1, 11)])
s2 = pd.Series([i for i in range(1, 11)], index=[i for i in range(1, 11)])
s3 = pd.Series({chr(i): i for i in range(97, 97 + 10)})
s1.index
s2.index
s3.index
s1.values
s2.values
s3.values
s3.dtype
s1.size
s1.astype('float64')

RangeIndex(start=0, stop=10, step=1)

Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

array([ 97,  98,  99, 100, 101, 102, 103, 104, 105, 106], dtype=int64)

dtype('int64')

10

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
dtype: float64

In [20]:
s1 = pd.Series([i for i in range(1, 11)], index=[i for i in range(2, 12)])
s1.loc[2]
s1.iloc[2]
s1

1

3

2      1
3      2
4      3
5      4
6      5
7      6
8      7
9      8
10     9
11    10
dtype: int64

In [21]:
s1 = pd.Series({chr(i): i for i in range(97,97+10)})
s1
s1.loc['a'] = 108
s1

a     97
b     98
c     99
d    100
e    101
f    102
g    103
h    104
i    105
j    106
dtype: int64

a    108
b     98
c     99
d    100
e    101
f    102
g    103
h    104
i    105
j    106
dtype: int64

In [22]:
s1 = pd.Series({chr(i): i for i in range(97, 97 + 10)})
s1.drop('a',inplace=True)
# s1
s1.drop(['b','c','d'],inplace=True)
# s1


b     98
c     99
d    100
e    101
f    102
g    103
h    104
i    105
j    106
dtype: int64

e    101
f    102
g    103
h    104
i    105
j    106
dtype: int64